version: '3'
services:
  postgres:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./sql/01-movies.sql:/docker-entrypoint-initdb.d/01-movies.sql
      - ./sql/02-artists.sql:/docker-entrypoint-initdb.d/02-artists.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5      

  graphql-api:
    container_name: graphql-api
    build: .
    ports:
      - 4000:4000
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: movies
      POSTGRES_PORT: 5432
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres


  


